[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open-browser"
version = "0.1"
description = "Open browser according to user preference"
requires-python = ">=3.9"

[project.scripts]
open-browser = "open_browser:main"
