#!/bin/bash

# Add a URL to Instapaper.
#
# Usage:
#
# $ instapaper <url> <title>
# https://newsboat.org/releases/2.25/docs/newsboat.html#_bookmarking

username=$INST_USERNAME
password=$INST_PASSWORD

curl "https://www.instapaper.com/api/add" --data-urlencode "username=$username" --data-urlencode "password=$password" --data-urlencode "url=$1" --data-urlencode "title=$2" > /dev/null & 
