_:

let
  # Dangerous commands that should be explicitly denied
  deniedShellCommands = [
    "rm -rf"
    "git push --force"
    "git reset --hard"
    "git clean -f"
    "terraform apply"
    "terraform destroy"
    "sbt publish"
  ];

  # Allowed shell commands (read-only and safe operations)
  allowedShellCommands = [
    "bd create"
    "bd close"
    "bd prime"
    "bd update"
    "bd ready"
    "bd show"
    "cat"
    "cd"
    "echo"
    "git add"
    "git branch"
    "git commit"
    "git diff"
    "git log"
    "git ls-files"
    "git remote -v"
    "git rev-parse"
    "git show"
    "git stash list"
    "git status"
    "jj abandon"
    "jj bookmark"
    "jj commit"
    "jj desc"
    "jj describe"
    "jj diff"
    "jj git"
    "jj log"
    "jj new"
    "jj root"
    "jj show"
    "jj status"
    "just build"
    "just lint"
    "just test"
    "just fmt"
    "ls"
    "find"
    "file"
    "grep"
    "head"
    "jq"
    "tail"
    "wc"
    "pwd"
    "rg"
    "sed"
    "stat"
    "statix check"
    "which"
    "tree"
    "mkdir"
    "sort"
    "uniq"
    "diff"
    "sbt"
    "npm run"
    "npm test"
    "npm install"
    "npm ci"
    "npx"
    "node"
    "go build"
    "go test"
    "go vet"
    "go fmt"
    "go mod tidy"
    "make"
    "terraform fmt"
    "terraform validate"
    "terraform plan"
    "gh auth"
    "gh pr"
    "gh issue"
    "gh repo view"
    "nix build"
    "nix flake"
    "nix develop"
    "nix fmt"
    "nix eval"
    "nix log"
    "nix path-info"
    "nix search"
    "nixfmt"
  ];
in
{
  inherit
    allowedShellCommands
    deniedShellCommands
    ;
}
