jobs:
  update-flakes-darwin:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: aleadag-nix-configs
      - name: 'Build Home-Manager configs for: t0'
        run: nix build --print-build-logs '.#homeConfigurations.t0.activationPackage'
name: update-flakes-darwin
"on":
  workflow_dispatch: null
  workflow_run:
    types:
      - completed
    workflows:
      - update-flakes
