jobs:
  update-flakes-aarch64-darwin:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: thiagokokada-nix-configs
      - name: 'Build Home-Manager configs for: home-mac'
        run: nix build --print-build-logs '.#homeConfigurations.home-mac.activationPackage'
      - name: 'Build nix-darwin configs for: t0'
        run: nix build --print-build-logs '.#darwinConfigurations.t0.system'
  update-flakes-aarch64-linux:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: thiagokokada-nix-configs
      - uses: thiagokokada/free-disk-space@main
        with:
          opt: true
          tool-cache: true
          usrlocal: true
          usrmisc: true
      - name: 'Build Home-Manager configs for: lckfb'
        run: nix build --print-build-logs '.#homeConfigurations.lckfb.activationPackage'
      - name: 'Build NixOS configs for: jetson-nixos'
        run: nix build --print-build-logs '.#nixosConfigurations.jetson-nixos.config.system.build.toplevel'
name: update-flakes-after
"on":
  workflow_dispatch: null
  workflow_run:
    types:
      - completed
    workflows:
      - update-flakes
